FROM node:18-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm i -y

COPY . ./

# start app
CMD ["npm", "dev"]
